version: '3'
services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://192.168.10.26:5050
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./app/node_modules
      - ./frontend:/app
  api:
    restart: anways
    build: ./api
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app
    
